# Generated by Django 6.1 on 2026-09-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gravewright_accounts", "0004_kallistisidentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="KallistisPlayerAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_code", models.CharField(max_length=16, unique=True)),
                (
                    "phrase_lookup_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("phrase_hash", models.CharField(editable=False, max_length=256)),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kallistis_player_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(player_code__startswith="JOGADOR-"),
                        name="accounts_player_access_code_prefix",
                    ),
                ],
            },
        ),
    ]
